# 標準の規約 + Railsの規約
Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.6.1
  # 除外するファイル
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - Gemfile
    - db/schema.rb

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

# Line is too long を無視
Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false
